# Use an official Python runtime as a base image
FROM python:3.8.13

RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Create non-root user
RUN useradd -ms /bin/bash python-api
USER python-api

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World

# Run app.py when the container launches
ENTRYPOINT ["python"]
CMD ["ETL-project.py"]